apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: froussel42/nginx_service:latest
        ports:
        - containerPort: 80

# docker build -t nginx_service .
# image: nginx_service%