FROM wordpress:php7.4-fpm-alpine

LABEL froussel <froussel@student.42.fr>

RUN apk update && apk upgrade && apk add nginx mysql-client \
&& apk add vim

COPY nginx.conf /etc/nginx/nginx.conf
COPY db_wordpress.sql /db_wordpress.sql
COPY start.sh /start.sh

EXPOSE 80

ENTRYPOINT sh /start.sh